[build]
  base = "frontend"
  publish = "dist"
  command = "pnpm run build"

[functions]
  directory = "../backend/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version" 