[phases.setup]
nixPkgs = ["python311", "pip", "gcc", "postgresql", "pkg-config"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Python Flask backend build complete'"]

[start]
cmd = "cd backend && python3 -m flask --app src.main run --host=0.0.0.0 --port=$PORT"

[variables]
PYTHONPATH = "/app/backend"