[phases.setup]
nixPkgs = ["python3", "gcc", "pkg-config"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "cd backend && python3 -m flask --app src.main run --host=0.0.0.0 --port=$PORT"