[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt && pip install -r backend/requirements.txt"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Main web service
[[services]]
name = "web"
source = "."
startCommand = "cd backend && gunicorn -w 4 -b 0.0.0.0:$PORT src.main:app"

[services.variables]
PYTHON_VERSION = "3.9.18"
PORT = "5001"
FLASK_ENV = "production"
FLASK_DEBUG = "False"

# Worker service for data monitoring
[[services]]
name = "worker"
source = "."
startCommand = "cd backend && python3 free_api_monitor.py"

[services.variables]
PYTHON_VERSION = "3.9.18"
FLASK_ENV = "production"
RAILWAY_ENVIRONMENT = "production" 