# Production Deployment Configuration
# ODB-1 Perplexity Cost Optimization - Phase 2

version: '3.8'

services:
  odb-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      
      # Redis Configuration
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      
      # Feature Flags - Phase 2 Optimization
      - FEATURE_REDIS_CACHE=true
      - FEATURE_PERFORMANCE_MONITORING=true
      - FEATURE_QUERY_OPTIMIZATION=true
      - FEATURE_INTELLIGENT_CACHING=true
      - FEATURE_RESPONSE_COMPRESSION=true
      - FEATURE_COST_TRACKING=true
      - FEATURE_CIRCUIT_BREAKER=true
      - FEATURE_GRACEFUL_DEGRADATION=true
      
      # Conservative flags (enable gradually)
      - FEATURE_CACHE_WARMING=false
      - FEATURE_REQUEST_BATCHING=false
      - FEATURE_DETAILED_ANALYTICS=false
      - FEATURE_PERFORMANCE_ALERTS=false
      - FEATURE_AUTO_SCALING=false
      
      # API Keys
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      
      # Flask Configuration
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  redis_data:

networks:
  default:
    name: odb-network 