[phases.setup]
nixPkgs = ["python39", "gcc", "python39Packages.pip"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "pip install -r requirements-base.txt",
  "pip install -r requirements-ml.txt"
]

[phases.build]
cmds = [
  "python -c 'from src.main import app'",
  "echo 'Build complete'"
]

[start]
cmd = "gunicorn --workers 4 --bind 0.0.0.0:$PORT --timeout 120 --access-logfile - --error-logfile - src.main:app" 