[phases.setup]
nixPkgs = ["python39", "gcc", "python39Packages.pip"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn --workers 2 --bind 0.0.0.0:$PORT src.main:app"
