name: Automated Contract Monitoring

on:
  schedule:
    - cron: '0 */1 * * *'    # Every hour
    - cron: '0 9 * * *'      # Daily at 9AM
    - cron: '0 8 * * 1'      # Weekly Monday 8AM
  workflow_dispatch:          # Manual trigger

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          
      - name: Run monitoring
        run: |
          cd backend
          python automated_monitoring.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
          SAM_GOV_API_KEY: ${{ secrets.SAM_GOV_API_KEY }} 